### ISSUE TITLE
Connecting to AWS Redshift 

### ISSUE THREAD

**Issue by ginokhumz** [kj-9/sqltools-redshift-driver#7]
Hi
So when I try connect to Redshift with SSL off I get the following error
```
no pg_hba.conf entry for host "::ffff:10.81.0.71", user "tes_dev", database "dev", SSL off
```

When I turn on SSL I get the following error
```
Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.cunpqpffnysy.eu-west-1.redshift.amazonaws.com
```

I'm using 
- Redshift Driver (dedicated ver) v0.0.4
- SQLTools v0.27.1
- VS Code Version: 1.79.0 

How do I solve this issue?

Thank you

**Comment by focused** [comment]
+1 I have the same issue, but I did not try an SSL connection.

**Comment by finalgrrrl** [comment]
having this same issue (including with SSL).

**Comment by finalgrrrl** [comment]
fyi @ginokhumz @focused i checked `requestCert` and was able to connect.

**Comment by ginokhumz** [comment]
@finalgrrrl Can you please elaborate a bit on what you mean.

Thanks

**Comment by finalgrrrl** [comment]
> @finalgrrrl Can you please elaborate a bit on what you mean.

i was seeing the same errors. when you enable SSL, several configuration options for SSL appear. enabling the `requestCert` option in that UI allowed me to connect.

**Comment by ginokhumz** [comment]
@finalgrrrl You are a Godsend. That fixed my issue. I also toggled `rejectUnauthorized` on and off and it ended up connecting.
